// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBe7UOzL8TrNdiDlWI0gI9mPBvXsSd6Y',
    appId: '1:24782972553:web:0ea1ef1caefec22fe0c858',
    messagingSenderId: '24782972553',
    projectId: 'llsps-1c751',
    authDomain: 'llsps-1c751.firebaseapp.com',
    storageBucket: 'llsps-1c751.firebasestorage.app',
    measurementId: 'G-QHJS052N2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6wt7y9v_wwo_k2L6G4Jr29c2o2FgZ7k',
    appId: '1:24782972553:android:c2daa0a920ae4ae4e0c858',
    messagingSenderId: '24782972553',
    projectId: 'llsps-1c751',
    storageBucket: 'llsps-1c751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJ9bVG_b5JtRnO4bpvrtzkUp1r-m_qIY',
    appId: '1:24782972553:ios:548b59766cb4014de0c858',
    messagingSenderId: '24782972553',
    projectId: 'llsps-1c751',
    storageBucket: 'llsps-1c751.firebasestorage.app',
    iosBundleId: 'com.example.llspsNew',
  );
}
